# General configurations
gpu: 0
seed: 0

# Path configurations
dataset_path: 'dataset'
log_path: 'log'
model_path: 'model'
config_path: ''
dataset_name: 'MNIST'
arch: ''
model_name: ''
config_file: ''

# Train configurations
train_dataset_ratio: 1.0
num_workers: 4
optim: 'AdamW'  # ['SGD', 'Adam', 'AdamW']
scheduler: 'StepLR'  # ['StepLR', 'Cosine']
lr: 0.0004
weight_decay: 0.0001
num_epochs: 20
step_size: 15
train_batch_size: 64
test_batch_size: 64
print_freq: 50
save_freq: 1

# Network configurations
num_classes: 10
embed_dim: 64
depth: 1
num_heads: 8
mlp_ratio: 4
sr_ratio: 8
qkv_bias: False
drop_path: 0.1
pos_encoding: True