# General configurations
gpu: 0
seed: 0

# Path configurations
dataset_path: 'dataset'
log_path: 'log'
model_path: 'model'
config_path: ''
dataset_name: 'MNIST'
arch: ''
model_name: ''
config_file: ''

# Train configurations
num_workers: 4
optim: 'Adam'  # ['SGD', 'Adam', 'AdamW']
scheduler: 'StepLR'  # ['StepLR', 'Cosine']
lr: 0.001
weight_decay: 0.0001
num_epochs: 20
step_size: 15
train_batch_size: 64
test_batch_size: 64
print_freq: 50
save_freq: 1

# Network configurations
RNN:
  in_dim: 28
  num_classes: 10
  hidden_size: 64
  num_layers: 1